version: '3'

services:
  node:
    build: 
      context: ./node
      dockerfile: Dockerfile.prod
    image: skyzenho/node:prod
    container_name: node
    # entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - node-net
    tty: true
    volumes: 
      - ./node:/usr/src/app
    ports:
      - "3000:3000"
    # depends_on:
    #   - db

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: skyzenho/nginx:prod
    container_name: nginx
    networks:
      - node-net
    ports:
      - "8080:80"

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-net
networks: 
  node-net:
    driver: bridge